### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by DimQ1** [TadaoYamaoka/RealtimeTranscribe#1]
Hi. Could you share your source code?
And detail guide how convert whisper to ONNX model.

**Comment by standyyyy** [comment]
Yes, I am also very interested in this. First of all, thank you for your sharing. I have read all your blogs about whisper and am amazed by your technical ability. If you can, you can share the converted ONNX model or let us know the details a little how to convert

**Comment by TadaoYamaoka** [comment]
I have published the source code of the conversion process to ONNX.
https://github.com/TadaoYamaoka/whisper
